# Generated by Django 3.0.4 on 2020-05-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_color_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
