# Generated by Django 3.0.4 on 2020-05-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200517_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='image',
            new_name='image_id',
        ),
    ]
