# Generated by Django 3.0.4 on 2020-05-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200520_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='image_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
