# Generated by Django 3.0.6 on 2020-05-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productlang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlang',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
