# Generated by Django 3.0.6 on 2020-05-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_categorylang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylang',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productlang',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
