# Generated by Django 3.0.6 on 2020-05-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20200530_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylang',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorylangs', to='product.Category'),
        ),
    ]
