# Generated by Django 3.0.4 on 2020-05-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='FAQ',
        ),
    ]
