# Generated by Django 3.0.6 on 2020-06-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200607_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
