# Generated by Django 3.0.6 on 2020-06-08 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200526_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='currency',
        ),
    ]
