# Generated by Django 3.0.6 on 2020-06-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofilex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfilex',
        ),
    ]
